name: RocketPlaceholdersAPI
version: 1.0
main: me.lorenzo0111.rpcookbook.RpCookbook
api-version: 1.15
authors: [ Lorenzo0111 ]
softdepend:
  - RocketPlaceholders
commands:
  rpcreate:
    description: Command to create a placeholder
  rplist:
    description: Command to view all registered placeholders